//! Crate-shared imports for the binding domains.

pub(crate) use pyo3::exceptions::{
    PyOSError, PyRuntimeError, PyTimeoutError, PyValueError,
};
pub(crate) use pyo3::prelude::*;
pub(crate) use pyo3::types::{PyAny, PyBytes, PyDict, PyList, PyTuple};
pub(crate) use sase_core::agent_archive::{
    agent_archive_facet_counts as core_agent_archive_facet_counts,
    mark_agent_archive_bundles_revived as core_mark_agent_archive_bundles_revived,
    query_agent_archive as core_query_agent_archive,
    validate_agent_archive_capabilities as core_validate_agent_archive_capabilities,
    validate_agent_archive_key as core_validate_agent_archive_key,
    validate_agent_archive_visibility as core_validate_agent_archive_visibility,
    verify_agent_archive_index as core_verify_agent_archive_index,
    AgentArchiveCapabilityValidationRequestWire, AgentArchiveFacetRequestWire,
    AgentArchiveKeyWire, AgentArchiveQueryRequestWire,
    AgentArchiveReviveMarkRequestWire, AgentArchiveVisibilityWire,
};
pub(crate) use sase_core::agent_artifact_run_retention::{
    apply_agent_artifact_run_retention as core_apply_agent_artifact_run_retention,
    AgentArtifactRunRetentionError, AgentArtifactRunRetentionRequestWire,
    AGENT_ARTIFACT_RUN_RETENTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::agent_clan_tribe::{
    resolve_clan_summary as core_resolve_clan_summary,
    resolve_clan_tribe as core_resolve_clan_tribe,
    ClanTribeResolutionRequestWire,
};
pub(crate) use sase_core::agent_cleanup::{
    cleanup_request_from_json_value,
    decide_force_reuse_stop_barrier as core_decide_force_reuse_stop_barrier,
    delete_agent_artifact_markers as core_delete_agent_artifact_markers,
    mark_comment_agents_as_killed as core_mark_comment_agents_as_killed,
    mark_hook_agents_as_killed as core_mark_hook_agents_as_killed,
    mark_mentor_agents_as_killed as core_mark_mentor_agents_as_killed,
    plan_agent_cleanup as core_plan_agent_cleanup,
    release_workspace_from_content as core_release_workspace_from_content,
    save_dismissed_agents_index as core_save_dismissed_agents_index,
    save_dismissed_bundle_json as core_save_dismissed_bundle_json,
    AgentCleanupIdentityWire, AgentCleanupRequestWire, AgentCleanupTargetWire,
    ForceReuseStopBarrierRequestWire,
};
pub(crate) use sase_core::agent_group_archive::{
    delete_dismissed_agent_group as core_delete_dismissed_agent_group,
    list_dismissed_agent_groups as core_list_dismissed_agent_groups,
    list_recent_dismissed_agent_groups as core_list_recent_dismissed_agent_groups,
    load_dismissed_agent_group as core_load_dismissed_agent_group,
    load_recent_dismissed_agent_group as core_load_recent_dismissed_agent_group,
    mark_dismissed_agent_group_revived as core_mark_dismissed_agent_group_revived,
    mark_recent_dismissed_agent_group_revived as core_mark_recent_dismissed_agent_group_revived,
    record_recent_dismissed_agent_group as core_record_recent_dismissed_agent_group,
    save_dismissed_agent_group as core_save_dismissed_agent_group,
    SavedAgentGroupWire,
};
pub(crate) use sase_core::agent_hold::{
    arm_agent_hold_relative as core_arm_agent_hold_relative,
    arm_agent_hold_until as core_arm_agent_hold_until,
    hold_blocks_candidate as core_hold_blocks_candidate,
    list_agent_holds as core_list_agent_holds,
    rebind_agent_hold_armer as core_rebind_agent_hold_armer,
    release_agent_hold as core_release_agent_hold,
    summarize_hold_capture as core_summarize_hold_capture, AgentHoldArmerWire,
    AgentHoldCandidateWire, AgentHoldCaptureIdentityWire,
    AgentHoldCaptureSummaryWire, AgentHoldError as AgentHoldDomainError,
    AgentHoldLivenessFactsWire, AgentHoldRecordWire, AgentHoldScopeWire,
    AgentHoldSelectorsWire,
};
pub(crate) use sase_core::agent_hold_deadlock::{
    hold_deadlock_reaches_candidate as core_hold_deadlock_reaches_candidate,
    HoldDeadlockCandidateWire, HoldDeadlockWaitNodeWire,
};
pub(crate) use sase_core::agent_identity::{
    agent_link_target as core_agent_link_target,
    agent_link_target_with_owner_roots as core_agent_link_target_with_owner_roots,
    agent_local_hood as core_agent_local_hood,
    agent_local_hood_with_owner_roots as core_agent_local_hood_with_owner_roots,
    agent_name_ancestors as core_agent_name_ancestors,
    agent_name_ancestors_with_owner_roots as core_agent_name_ancestors_with_owner_roots,
    agent_name_in_hood as core_agent_name_in_hood,
    agent_name_in_hood_with_owner_roots as core_agent_name_in_hood_with_owner_roots,
    foreign_agent_owner_root as core_foreign_agent_owner_root,
    globalize_agent_name as core_globalize_agent_name,
    globalize_owned_agent_name as core_globalize_owned_agent_name,
    normalize_agent_archive_name as core_normalize_agent_archive_name,
    normalize_owned_agent_name as core_normalize_owned_agent_name,
    parse_agent_session_name as core_parse_agent_session_name,
    parse_owned_agent_name as core_parse_owned_agent_name,
    project_agent_relationship_graph as core_project_agent_relationship_graph,
    rewrite_agent_relationship_batch as core_rewrite_agent_relationship_batch,
    strip_global_agent_name as core_strip_global_agent_name,
    validate_agent_name as core_validate_agent_name,
    validate_agent_relationship_batch as core_validate_agent_relationship_batch,
    validate_agent_username as core_validate_agent_username,
    validate_owned_agent_name as core_validate_owned_agent_name,
    validate_owner_root as core_validate_owner_root, AgentOwnerIdentity,
    AgentRelationshipBatchWire, AGENT_RELATIONSHIP_SCHEMA_VERSION,
};
pub(crate) use sase_core::agent_launch::{
    admission_unit_results as core_admission_unit_results,
    agent_unit_dispatch_prompt_with_flags as core_agent_unit_dispatch_prompt_with_flags,
    allocate_and_claim_workspace_from_content as core_allocate_and_claim_workspace_from_content,
    allocate_launch_timestamp_batch as core_allocate_launch_timestamp_batch,
    bind_batch_predecessor_waits as core_bind_batch_predecessor_waits,
    build_condition_context as core_build_condition_context,
    classify_condition_status as core_classify_condition_status,
    cleanup_proc_private_inputs as core_cleanup_proc_private_inputs,
    decide_workspace_occupant_conflict as core_decide_workspace_occupant_conflict,
    dispatch_fingerprint as core_dispatch_fingerprint,
    evaluate_launch_condition as core_evaluate_launch_condition,
    filter_conditional_launch_segments as core_filter_conditional_launch_segments,
    launch_unit_hold_armer as core_launch_unit_hold_armer,
    launch_unit_hold_key as core_launch_unit_hold_key,
    list_workspace_claims_from_content as core_list_workspace_claims_from_content,
    next_admission_actions_with_holds as core_next_admission_actions_with_holds,
    parse_proc_duration_seconds as core_parse_proc_duration_seconds,
    plan_agent_launch_fanout as core_plan_agent_launch_fanout,
    plan_claim_workspace_from_content as core_plan_claim_workspace_from_content,
    plan_transfer_workspace_claim_from_content as core_plan_transfer_workspace_claim_from_content,
    plan_typed_launch_units_with_flags as core_plan_typed_launch_units_with_flags,
    prepare_agent_launch as core_prepare_agent_launch,
    prepare_proc_script as core_prepare_proc_script,
    proc_script_argv as core_proc_script_argv,
    prompt_has_identity_directive as core_prompt_has_identity_directive,
    reconcile_admission_journal as core_reconcile_admission_journal,
    resolve_proc_execution_cwd as core_resolve_proc_execution_cwd,
    sanitize_safe_inputs as core_sanitize_safe_inputs,
    sanitized_proc_env as core_sanitized_proc_env,
    summarize_admission as core_summarize_admission,
    validate_proc_workspace_intent as core_validate_proc_workspace_intent,
    validate_standalone_proc_shell_name as core_validate_standalone_proc_shell_name,
    wait_target_key as core_wait_target_key, AgentLaunchPreparedWire,
    AgentLaunchRequestWire, AgentUnitWire, BatchPredecessorContextWire,
    ConditionEvalRequestWire, LaunchAdmissionHoldBlockWire,
    LaunchAdmissionJournalEntryWire, LaunchAdmissionUnitStateWire,
    LaunchAdmissionWaitFactWire, LaunchPlanWire, LaunchUnitPayloadWire,
    LaunchUnitWire, OccupancyCallerWire, OccupantRecordWire,
    ProcDispatchRequestWire, WaitTargetWire, WaitedOutcomeWire,
    WorkspaceClaimRequestWire, WorkspaceClaimWire,
    CONDITION_CONTEXT_SCHEMA_VERSION, CONDITION_DEFAULT_TIMEOUT_SECONDS,
    CONDITION_EVAL_WIRE_SCHEMA_VERSION, CONDITION_MAX_TIMEOUT_SECONDS,
    CONDITION_OUTPUT_CAP_BYTES, LAUNCH_ADMISSION_JOURNAL_SCHEMA_VERSION,
    PROC_DISPATCH_WIRE_SCHEMA_VERSION, XPROMPT_PROC_ORIGIN,
};
pub(crate) use sase_core::agent_name_template::{
    agent_name_template_key as core_agent_name_template_key,
    agent_name_template_namespace_template as core_agent_name_template_namespace_template,
    agent_name_template_tokens_after as core_agent_name_template_tokens_after,
    compare_agent_name_template_tokens as core_compare_agent_name_template_tokens,
    is_agent_name_template as core_is_agent_name_template,
    iter_agent_name_key_markers as core_iter_agent_name_key_markers,
    match_agent_name_template as core_match_agent_name_template,
    parse_agent_name_template as core_parse_agent_name_template,
    render_agent_name_template as core_render_agent_name_template,
    AgentNameTemplateKey,
};
pub(crate) use sase_core::agent_ownership::{
    agent_ownership_batch_request_from_json_value,
    plan_agent_ownership_batch as core_plan_agent_ownership_batch,
};
pub(crate) use sase_core::agent_publication_batches::{
    plan_agent_publication_batches as core_plan_agent_publication_batches,
    AgentPublicationPathRecordWire,
};
pub(crate) use sase_core::agent_runtime::{
    aggregate_clan_runtime as core_aggregate_clan_runtime,
    ClanRuntimeMemberWire,
};
pub(crate) use sase_core::agent_scan::{
    agent_artifact_index_status as core_agent_artifact_index_status,
    canonical_agent_artifact_path as core_canonical_agent_artifact_path,
    collect_workflow_artifact_candidates as core_collect_workflow_artifact_candidates,
    delete_agent_artifact_index_row as core_delete_agent_artifact_index_row,
    delete_agent_artifact_index_row_with_busy_timeout as core_delete_agent_artifact_index_row_with_busy_timeout,
    find_gate_shell_by_gate_id as core_find_gate_shell_by_gate_id,
    load_agent_artifact_records as core_load_agent_artifact_records,
    parse_agent_artifact_path as core_parse_agent_artifact_path,
    parse_output_variable_selector as core_parse_output_variable_selector,
    prune_hidden_terminal_agent_artifact_index_rows as core_prune_hidden_terminal_agent_artifact_index_rows,
    query_agent_alias_history as core_query_agent_alias_history,
    query_agent_artifact_index as core_query_agent_artifact_index,
    query_agent_output_variable_history as core_query_agent_output_variable_history,
    query_agent_output_variable_selectors as core_query_agent_output_variable_selectors,
    query_related_agent_artifact_dirs as core_query_related_agent_artifact_dirs,
    read_agent_artifact_index_meta as core_read_agent_artifact_index_meta,
    rebuild_agent_artifact_index as core_rebuild_agent_artifact_index,
    reconcile_agent_artifact_index_dismissed_agent_session_members as core_reconcile_agent_artifact_index_dismissed_agent_session_members,
    replace_agent_artifact_index_dismissed_agents_with_force as core_replace_agent_artifact_index_dismissed_agents_with_force,
    resolve_agent_artifact_path as core_resolve_agent_artifact_path,
    resolve_agent_artifact_timestamp_path as core_resolve_agent_artifact_timestamp_path,
    scan_agent_artifact_dirs as core_scan_agent_artifact_dirs,
    scan_agent_artifacts as core_scan_agent_artifacts,
    terminalize_stale_active_agent_artifact_index_rows as core_terminalize_stale_active_agent_artifact_index_rows,
    upsert_agent_artifact_index_row as core_upsert_agent_artifact_index_row,
    vacuum_agent_artifact_index as core_vacuum_agent_artifact_index,
    write_agent_artifact_index_meta as core_write_agent_artifact_index_meta,
    AgentAliasHistoryQueryWire, AgentArtifactIndexQueryWire,
    AgentArtifactScanOptionsWire, AgentOutputVariableHistoryQueryWire,
    AgentOutputVariableSelectorQueryWire, OutputVariableSelectorError,
    AGENT_ALIAS_HISTORY_WIRE_SCHEMA_VERSION,
    AGENT_OUTPUT_VARIABLE_HISTORY_WIRE_SCHEMA_VERSION,
    AGENT_OUTPUT_VARIABLE_SELECTOR_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::agent_session::{
    resolve_agent_session_parent as core_resolve_agent_session_parent,
    AgentSessionParentResolutionRequestWire,
};
pub(crate) use sase_core::agent_stats::{
    query_activity_stats as core_query_activity_stats,
    query_run_stats as core_query_run_stats, AgentActivityStatsRequestWire,
    AgentRunStatsRequestWire,
};
pub(crate) use sase_core::agent_tribe::{
    agent_tribe_display_key as core_agent_tribe_display_key,
    canonicalize_agent_tribe_metadata as core_canonicalize_agent_tribe_metadata,
    canonicalize_public_tribe_name as core_canonicalize_public_tribe_name,
    is_reserved_tribe_name as core_is_reserved_tribe_name,
    parse_tribe_reference as core_parse_tribe_reference,
    public_tribe_name as core_public_tribe_name,
    reserved_tribe_target_reason as core_reserved_tribe_target_reason,
    resolve_agent_tribe_display_config as core_resolve_agent_tribe_display_config,
    resolve_agent_tribe_identity as core_resolve_agent_tribe_identity,
    validate_tribe_name as core_validate_tribe_name,
    AgentTribeDisplayResolutionRequestWire,
    AgentTribeError as AgentTribeDomainError,
    AgentTribeIdentityResolutionRequestWire,
};
pub(crate) use sase_core::artifact_consumption::{
    read_artifact_consumption_log as core_read_artifact_consumption_log,
    summarize_artifact_consumption as core_summarize_artifact_consumption,
    ARTIFACT_CONSUMPTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::artifact_file::{
    artifact_file_store_economics as core_artifact_file_store_economics,
    list_artifact_file_trash as core_list_artifact_file_trash,
    materialize_vcs_artifact_file as core_materialize_vcs_artifact_file,
    plan_artifact_file_retention as core_plan_artifact_file_retention,
    purge_artifact_file_trash as core_purge_artifact_file_trash,
    query_artifact_context as core_query_artifact_context,
    query_artifact_files as core_query_artifact_files,
    restore_artifact_file_trash as core_restore_artifact_file_trash,
    trash_artifact_file as core_trash_artifact_file,
    ArtifactContextProducerGroupWire, ArtifactFileEconomicsOptionsWire,
    ArtifactFileQueryError, ArtifactFileQueryFiltersWire,
    ArtifactFileRetentionPolicyWire, ArtifactFileTrashPurgeRequestWire,
    ArtifactFileTrashRequestWire, ArtifactFileTrashRestoreRequestWire,
    ArtifactFileVcsMaterializationRequestWire,
    ARTIFACT_CONTEXT_QUERY_WIRE_SCHEMA_VERSION,
    ARTIFACT_FILE_LIFECYCLE_WIRE_SCHEMA_VERSION,
    ARTIFACT_FILE_QUERY_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::artifact_link::{
    artifact_link_alias_producer_id as core_artifact_link_alias_producer_id,
    artifact_link_cutover_attestation as core_artifact_link_cutover_attestation,
    artifact_link_cutover_baseline_event as core_artifact_link_cutover_baseline_event,
    artifact_link_cutover_import_identity as core_artifact_link_cutover_import_identity,
    artifact_link_cutover_marker as core_artifact_link_cutover_marker,
    artifact_link_cutover_marker_canonical_json as core_artifact_link_cutover_marker_canonical_json,
    artifact_link_cutover_progress as core_artifact_link_cutover_progress,
    artifact_link_cutover_read_state as core_artifact_link_cutover_read_state,
    artifact_link_derived_producer_id as core_artifact_link_derived_producer_id,
    artifact_link_event_canonical_json as core_artifact_link_event_canonical_json,
    artifact_link_event_digest as core_artifact_link_event_digest,
    artifact_link_event_owner_requirements as core_artifact_link_event_owner_requirements,
    artifact_link_event_path_for_digest as core_artifact_link_event_path_for_digest,
    artifact_link_event_validate_bytes as core_artifact_link_event_validate_bytes,
    artifact_link_event_validate_path as core_artifact_link_event_validate_path,
    artifact_link_machine_run_id as core_artifact_link_machine_run_id,
    artifact_link_outbox_classify_line as core_artifact_link_outbox_classify_line,
    artifact_link_outbox_legacy_conversion as core_artifact_link_outbox_legacy_conversion,
    artifact_link_publication_due as core_artifact_link_publication_due,
    artifact_link_publication_mark_attempt as core_artifact_link_publication_mark_attempt,
    artifact_link_publication_receipt as core_artifact_link_publication_receipt,
    artifact_link_publication_record_key as core_artifact_link_publication_record_key,
    artifact_link_publication_register_pending as core_artifact_link_publication_register_pending,
    artifact_link_stable_fact_created_at as core_artifact_link_stable_fact_created_at,
    artifact_link_stable_operation_id as core_artifact_link_stable_operation_id,
    artifact_md_path as core_artifact_md_path,
    artifact_row_index_keys as core_artifact_row_index_keys,
    artifact_row_ref_lookup_keys as core_artifact_row_ref_lookup_keys,
    builtin_artifact_relations as core_builtin_artifact_relations,
    canonicalize_artifact_link_alias as core_canonicalize_artifact_link_alias,
    canonicalize_artifact_link_event_json_value as core_canonicalize_artifact_link_event_json_value,
    canonicalize_artifact_link_ref as core_canonicalize_artifact_link_ref,
    companion_md_path as core_companion_md_path,
    lookup_artifact_relation as core_lookup_artifact_relation,
    merge_artifact_link_indexes as core_merge_artifact_link_indexes,
    parse_artifact_link_cutover_marker as core_parse_artifact_link_cutover_marker,
    parse_artifact_link_frontmatter_inlet as core_parse_artifact_link_frontmatter_inlet,
    parse_artifact_link_ref_parts as core_parse_artifact_link_ref_parts,
    parse_links_block as core_parse_links_block,
    reduce_link_events as core_reduce_link_events,
    relation_label_from_perspective as core_relation_label_from_perspective,
    remove_links_block as core_remove_links_block,
    render_links_block as core_render_links_block,
    resolve_artifact_link_event_aliases as core_resolve_artifact_link_event_aliases,
    resolve_artifact_row_identity as core_resolve_artifact_row_identity,
    strip_links_block as core_strip_links_block,
    upsert_artifact_link_row as core_upsert_artifact_link_row,
    upsert_links_block as core_upsert_links_block,
    validate_artifact_link_row as core_validate_artifact_link_row,
    ArtifactLinkAliasWire, ArtifactLinkCutoverBaselineEventRequestWire,
    ArtifactLinkCutoverBaselineEventWire, ArtifactLinkCutoverEventStoreWire,
    ArtifactLinkCutoverImportIdentityWire,
    ArtifactLinkCutoverImportRequestWire, ArtifactLinkCutoverMarkerWire,
    ArtifactLinkCutoverProgressRequestWire, ArtifactLinkCutoverReadRootWire,
    ArtifactLinkCutoverRoleWire, ArtifactLinkCutoverStateWire,
    ArtifactLinkError, ArtifactLinkEventWire, ArtifactLinkIndexWire,
    ArtifactLinkOriginWire, ArtifactLinkOwnerRequirementWire,
    ArtifactLinkPublicationAttemptWire, ArtifactLinkPublicationEvidenceWire,
    ArtifactLinkPublicationObservationWire, ArtifactLinkPublicationRecordWire,
    ArtifactLinkRowWire, ArtifactMdPathRequestWire, ArtifactRowIdentityWire,
    ArtifactRowRefQueryWire, BeadLinkDirectionWire, ManagedTableTableWire,
    ARTIFACT_LINK_CUTOVER_WIRE_SCHEMA_VERSION,
    ARTIFACT_LINK_EVENT_WIRE_SCHEMA_VERSION,
    ARTIFACT_LINK_PUBLICATION_OWNERSHIP_WIRE_SCHEMA_VERSION,
    ARTIFACT_LINK_PUBLICATION_STATE_WIRE_SCHEMA_VERSION,
    ARTIFACT_LINK_ROW_SCHEMA_VERSION,
    ARTIFACT_ROW_RESOLUTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::artifact_link_eligibility::{
    artifact_link_release_evidence as core_artifact_link_release_evidence,
    decide_artifact_link_eligibility as core_decide_artifact_link_eligibility,
    validate_artifact_link_release_evidence as core_validate_artifact_link_release_evidence,
    ArtifactLinkEligibilityDecisionWire, ArtifactLinkEligibilityError,
    ArtifactLinkEligibilityRequestWire, ArtifactLinkReleaseEvidenceWire,
    ARTIFACT_LINK_ELIGIBILITY_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::artifact_object_store::{
    artifact_object_prompt_link as core_artifact_object_prompt_link,
    artifact_object_relpath as core_artifact_object_relpath,
};
pub(crate) use sase_core::artifact_ref::{
    artifact_ref_kind_catalog as core_artifact_ref_kind_catalog,
    artifact_ref_provider_spec_digest as core_artifact_ref_provider_spec_digest,
    canonical_artifact_ref_kind as core_canonical_artifact_ref_kind,
    canonicalize_artifact_ref as core_canonicalize_artifact_ref,
    filter_artifact_ref_path_payloads as core_filter_artifact_ref_path_payloads,
    fold_artifact_ref_files as core_fold_artifact_ref_files,
    normalize_artifact_ref_list as core_normalize_artifact_ref_list,
    parse_artifact_ref as core_parse_artifact_ref,
    parse_artifact_ref_canonical as core_parse_artifact_ref_canonical,
    parse_artifact_ref_file_index as core_parse_artifact_ref_file_index,
    parse_artifact_ref_list as core_parse_artifact_ref_list,
    parse_artifact_ref_use_manifest as core_parse_artifact_ref_use_manifest,
    quote_artifact_ref_argument as core_quote_artifact_ref_argument,
    render_artifact_ref as core_render_artifact_ref,
    render_artifact_ref_expansion as core_render_artifact_ref_expansion,
    render_artifact_ref_file_row as core_render_artifact_ref_file_row,
    render_artifact_ref_use_record as core_render_artifact_ref_use_record,
    resolve_artifact_ref as core_resolve_artifact_ref,
    resolve_artifact_ref_list as core_resolve_artifact_ref_list,
    resolve_document_source_target as core_resolve_document_source_target,
    scan_artifact_ref_document_links as core_scan_artifact_ref_document_links,
    scan_artifact_refs as core_scan_artifact_refs,
    split_link_location as core_split_link_location,
    validate_artifact_entry as core_validate_artifact_entry,
    validate_artifact_ref_expansion_format as core_validate_artifact_ref_expansion_format,
    validate_artifact_ref_file_row as core_validate_artifact_ref_file_row,
    validate_artifact_ref_provider_spec as core_validate_artifact_ref_provider_spec,
    ArtifactEntryWire, ArtifactRefContextWire, ArtifactRefDocumentOwnerWire,
    ArtifactRefError, ArtifactRefFileVersionRowWire,
    ArtifactRefProviderSpecWire, ArtifactRefUseRecordWire,
    ParsedArtifactRefWire, ARTIFACT_REF_CONTEXT_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_DOCUMENT_SCAN_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_ENTRY_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_EXPANSION_PLACEHOLDERS,
    ARTIFACT_REF_FILE_INDEX_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_LIST_RESOLUTION_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_PARSE_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_PATH_FILTER_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_PROVIDER_SPEC_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_RESOLUTION_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_TARGET_RESOLUTION_WIRE_SCHEMA_VERSION,
    ARTIFACT_REF_USE_WIRE_SCHEMA_VERSION, LINK_LOCATION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::axe_chop::{
    apply_checkpoint_update as core_apply_checkpoint_update,
    check_and_record_once_per as core_check_and_record_once_per,
    derive_chop_agent_name as core_derive_chop_agent_name,
    evaluate_chop_decision as core_evaluate_chop_decision,
    expand_chop_targets as core_expand_chop_targets,
    normalize_chop_subprocess_diagnostic as core_normalize_chop_subprocess_diagnostic,
    parse_chop_duration as core_parse_chop_duration,
    parse_chop_result as core_parse_chop_result,
    release_chop_once_per as core_release_chop_once_per,
    split_axe_description as core_split_axe_description,
    validate_axe_config as core_validate_axe_config,
    validate_chop_proposal as core_validate_chop_proposal,
    validate_chop_result as core_validate_chop_result,
    AxeConfigValidationRequestWire, ChopCheckpointUpdateRequestWire,
    ChopDecisionRequestWire, ChopEngineError, ChopLaunchProposalWire,
    ChopOncePerReleaseRequestWire, ChopOncePerRequestWire,
    ChopResultDocumentWire, ChopSubprocessDiagnosticRequestWire,
    ChopTargetExpansionRequestWire, CHOP_ENGINE_SCHEMA_VERSION,
    CHOP_RESULT_SCHEMA_VERSION, CHOP_STATE_SCHEMA_VERSION,
};
pub(crate) use sase_core::axe_overrun::{
    classify_chop_overrun as core_classify_chop_overrun, ChopOverrunError,
    ChopOverrunRequestWire, CHOP_OVERRUN_SCHEMA_VERSION,
};
pub(crate) use sase_core::axe_status::{
    classify_axe_status as core_classify_axe_status,
    project_axe_status_public as core_project_axe_status_public,
    AxeStatusError, AxeStatusRequestWire, AxeStatusSnapshotWire,
    AXE_STATUS_SCHEMA_VERSION,
};
#[cfg(test)]
pub(crate) use sase_core::bead::PhaseSizeWire;
pub(crate) use sase_core::bead::{
    add_bead_link as core_bead_add_link,
    add_dependency as core_bead_add_dependency,
    add_task_plus_one as core_bead_add_task_plus_one,
    append_issue_note as core_bead_append_issue_note,
    bead_history as core_bead_history, bead_lost_notes as core_bead_lost_notes,
    bead_touch_index_status as core_bead_touch_index_status,
    blocked_issues as core_bead_blocked_issues,
    build_epic_work_plan as core_bead_build_epic_work_plan,
    build_epic_work_plan_from_issues as core_bead_build_epic_work_plan_from_issues,
    cancel_task_snooze as core_bead_cancel_task_snooze,
    claim_for_agent_launch as core_bead_claim_for_agent_launch,
    claim_for_agent_wait as core_bead_claim_for_agent_wait,
    close_issues_with_note as core_bead_close_issues_with_note,
    create_issue as core_bead_create_issue, doctor as core_bead_doctor,
    doctor_report as core_bead_doctor_report,
    doctor_report_with_contexts as core_bead_doctor_report_with_contexts,
    doctor_with_contexts as core_bead_doctor_with_contexts,
    drop_flag_type_migration_sql as core_bead_drop_flag_type_migration_sql,
    edit_issue_note as core_bead_edit_issue_note,
    execute_bead_cli as core_execute_bead_cli,
    export_jsonl as core_bead_export_jsonl,
    external_ref_migration_sql as core_bead_external_ref_migration_sql,
    flag_type_migration_sql as core_bead_flag_type_migration_sql,
    get_epic_children as core_bead_get_epic_children,
    init_store as core_bead_init_store, list_issues as core_bead_list_issues,
    mark_ready_to_work as core_bead_mark_ready_to_work,
    merge_bead_event_streams as core_merge_bead_event_streams,
    merge_bead_event_streams_with_relocation as core_merge_bead_event_streams_with_relocation,
    needs_drop_flag_type_migration as core_bead_needs_drop_flag_type_migration,
    needs_external_ref_migration as core_bead_needs_external_ref_migration,
    needs_flag_type_migration as core_bead_needs_flag_type_migration,
    needs_plus_one_evidence_migration as core_bead_needs_plus_one_evidence_migration,
    needs_resolution_migration as core_bead_needs_resolution_migration,
    needs_size_check_relax_migration as core_bead_needs_size_check_relax_migration,
    needs_snoozed_status_migration as core_bead_needs_snoozed_status_migration,
    needs_task_ready_migration as core_bead_needs_task_ready_migration,
    needs_task_type_migration as core_bead_needs_task_type_migration,
    open_issue as core_bead_open_issue,
    plus_one_evidence_migration_sql as core_bead_plus_one_evidence_migration_sql,
    preclaim_epic_work_plan as core_bead_preclaim_epic_work_plan,
    prune_removed_flag_event_streams as core_bead_prune_removed_flag_event_streams,
    query_bead_touches as core_query_bead_touches,
    read_event_store_issues as core_bead_read_event_store_issues,
    read_legacy_jsonl_issues as core_bead_read_legacy_jsonl_issues,
    read_store_issues as core_bead_read_store_issues,
    ready_issues as core_bead_ready_issues,
    reduce_event_streams as core_reduce_event_streams,
    refresh_bead_touch_index as core_refresh_bead_touch_index,
    release_agent_claim as core_bead_release_agent_claim,
    remove_bead_link as core_bead_remove_link,
    remove_dependencies as core_bead_remove_dependencies,
    remove_issue as core_bead_remove_issue,
    remove_issue_note as core_bead_remove_issue_note,
    remove_issues as core_bead_remove_issues,
    repair_event_store_manifest as core_repair_event_store_manifest,
    resolution_migration_sql as core_bead_resolution_migration_sql,
    resolve_issue_id as core_bead_resolve_issue_id,
    route_bead_targets as core_bead_route_targets,
    search_issues as core_bead_search_issues,
    set_bead_link_projection as core_bead_set_link_projection,
    set_bead_link_projections as core_bead_set_link_projections,
    show_issue as core_bead_show_issue,
    show_issue_detail_with_options as core_bead_show_issue_detail,
    size_check_relax_migration_sql as core_bead_size_check_relax_migration_sql,
    snooze_task as core_bead_snooze_task,
    snoozed_status_migration_sql as core_bead_snoozed_status_migration_sql,
    stats as core_bead_stats, sync_is_clean as core_bead_sync_is_clean,
    task_ready_migration_sql as core_bead_task_ready_migration_sql,
    task_type_migration_sql as core_bead_task_type_migration_sql,
    unmark_ready_to_work as core_bead_unmark_ready_to_work,
    update_issue as core_bead_update_issue,
    update_issues as core_bead_update_issues, BeadCreateRequestWire, BeadError,
    BeadEventStoreManifestWire, BeadEventStreamWire,
    BeadLinkProjectionRequestWire, BeadPreclaimAssignmentWire,
    BeadResolutionWire, BeadTargetRoutingRequestWire, BeadUpdateFieldsWire,
    IssueWire, BEAD_TARGET_ROUTING_WIRE_SCHEMA_VERSION,
    BEAD_TOUCH_INDEX_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::bead_action::{
    decide_bead_action_from_json as core_decide_bead_action_from_json,
    parse_bead_action_field as core_parse_bead_action_field,
    validate_finalizer_assigned_bead_binding as core_validate_finalizer_assigned_bead_binding,
    validate_finalizer_bead_decision_from_json as core_validate_finalizer_bead_decision_from_json,
    BeadActionError, BEAD_ACTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::commit_footer::{
    parse_commit_footer as core_parse_commit_footer,
    update_commit_footer as core_update_commit_footer, CommitFooterUpdateWire,
    COMMIT_FOOTER_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::commit_sha::commit_shas_equivalent as core_commit_shas_equivalent;
pub(crate) use sase_core::commit_subject::{
    default_commit_subject_types as core_default_commit_subject_types,
    parse_commit_subject as core_parse_commit_subject,
    COMMIT_SUBJECT_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::config::{
    compose_axe_config as core_compose_axe_config,
    config_field_model as core_config_field_model,
    config_inventory as core_config_inventory,
    config_plan_edit as core_config_plan_edit,
    config_validate as core_config_validate,
    plan_axe_entry_mutation as core_plan_axe_entry_mutation,
    AxeConfigComposeRequestWire, AxeEntryMutationRequestWire,
    ConfigEditRequestWire, ConfigError as ConfigDomainError,
    ConfigInventoryRequestWire, ConfigValidateRequestWire,
};
pub(crate) use sase_core::content_layout::{
    memory_note_issue as core_memory_note_issue,
    memory_reference_name as core_memory_reference_name,
    memory_reference_stem as core_memory_reference_stem,
    reserved_memory_namespace_issue as core_reserved_memory_namespace_issue,
    resolve_layout_candidates as core_resolve_layout_candidates,
    sase_content_layout as core_sase_content_layout,
    skill_placement_issue as core_skill_placement_issue,
    skill_reference_name as core_skill_reference_name,
    LayoutCollisionPolicyWire,
};
pub(crate) use sase_core::continuation::{
    bind_conditional_completion as core_bind_conditional_completion,
    consume_conditional_completion_request as core_consume_conditional_completion,
    decide_resume_adoption as core_decide_resume_adoption,
    evaluate_conditional_completion as core_evaluate_conditional_completion,
    freeze_continuation_policy as core_freeze_continuation_policy,
    invalidate_conditional_completion_request as core_invalidate_conditional_completion,
    new_continuation_delivery_record as core_new_continuation_delivery_record,
    plan_continuation_budget as core_plan_continuation_budget,
    plan_continuation_replay as core_plan_continuation_replay,
    plan_continuation_retention as core_plan_continuation_retention,
    preview_conditional_completion as core_preview_conditional_completion,
    render_conditional_completion_message_request as core_render_conditional_completion_message,
    resolve_continuation_policy as core_resolve_continuation_policy,
    rollback_conditional_completion_binding as core_rollback_conditional_completion_binding,
    seal_conditional_completion as core_seal_conditional_completion,
    select_continuation_evidence as core_select_continuation_evidence,
    transition_continuation_delivery as core_transition_continuation_delivery,
    validate_agent_delta as core_validate_agent_delta,
    validate_conditional_completion_intent as core_validate_conditional_completion_intent,
    validate_continuation_delivery_record as core_validate_continuation_delivery_record,
    validate_continuation_graph as core_validate_continuation_graph,
    validate_continuation_intent as core_validate_continuation_intent,
    validate_continuation_node_value as core_validate_continuation_node_value,
    validate_continuation_policy as core_validate_continuation_policy,
    validate_diagnostic_manifest as core_validate_diagnostic_manifest,
    validate_launch_requester_continuation as core_validate_launch_requester_continuation,
    validate_monitor_result as core_validate_monitor_result, AgentDeltaWire,
    ConditionalCompletionBindRequestWire,
    ConditionalCompletionConsumeRequestWire,
    ConditionalCompletionEvaluateRequestWire, ConditionalCompletionIntentWire,
    ConditionalCompletionMessageRequestWire,
    ConditionalCompletionPrepareRequestWire,
    ConditionalCompletionRollbackRequestWire, ContinuationBudgetRequestWire,
    ContinuationDeliveryNewRequestWire, ContinuationDeliveryRecordWire,
    ContinuationDeliveryTransitionRequestWire, ContinuationError,
    ContinuationEvidenceSelectionRequestWire, ContinuationIntentWire,
    ContinuationNodeWire, ContinuationOutcomePolicyWire,
    ContinuationPolicyFreezeRequestWire,
    ContinuationPolicyResolutionRequestWire, ContinuationReplayPlanRequestWire,
    ContinuationResumeAdoptionRequestWire, ContinuationRetentionRequestWire,
    DiagnosticManifestWire, LaunchRequesterContinuationWire, MonitorResultWire,
    CONTINUATION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::disk_cleanup_outcome::{
    normalize_disk_cleanup_outcome as core_normalize_disk_cleanup_outcome,
    DiskCleanupOutcomeError, DiskCleanupOutcomeRequestWire,
    DISK_CLEANUP_OUTCOME_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::disk_inventory::{
    classify_disk_inventory as core_classify_disk_inventory,
    DiskInventoryError, DiskInventoryRequestWire,
    DISK_INVENTORY_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::disk_pressure::{
    classify_disk_pressure as core_classify_disk_pressure, DiskPressureError,
    DiskPressureRequestWire, DISK_PRESSURE_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::effort::resolve_effective_effort as core_resolve_effective_effort;
pub(crate) use sase_core::effort_override::{
    clear_effort_override as core_clear_effort_override,
    get_effort_override as core_get_effort_override,
    set_effort_override_relative as core_set_effort_override_relative,
    set_effort_override_until as core_set_effort_override_until,
    EffortOverrideError as EffortOverrideDomainError,
};
pub(crate) use sase_core::external_pr::{
    canonical_pull_request_url as core_canonical_pull_request_url,
    plan_external_pr_import as core_plan_external_pr_import,
    ExternalPrImportRequestWire,
};
pub(crate) use sase_core::feature_flag_state::{
    feature_flag_state_get as core_feature_flag_state_get,
    feature_flag_state_reconcile as core_feature_flag_state_reconcile,
    feature_flag_state_set as core_feature_flag_state_set,
    FeatureFlagStateError as FeatureFlagStateDomainError,
};
pub(crate) use sase_core::fenced_block_details_wire as core_fenced_block_details_wire;
pub(crate) use sase_core::fenced_block_ranges as core_fenced_block_ranges;
pub(crate) use sase_core::finalizer::{
    aggregate_finalizer_outcomes as core_aggregate_finalizer_outcomes,
    authenticate_finalizer_plan as core_authenticate_finalizer_plan,
    finalizer_context_digest as core_finalizer_context_digest,
    finalizer_digest_json_value as core_finalizer_digest_json_value,
    finalizer_instance_spec_digest as core_finalizer_instance_spec_digest,
    finalizer_plan_digest as core_finalizer_plan_digest,
    finalizer_provider_spec_digest as core_finalizer_provider_spec_digest,
    resolve_finalizer_plan as core_resolve_finalizer_plan,
    select_remaining_commit_obligations as core_select_remaining_commit_obligations,
    validate_finalizer_context as core_validate_finalizer_context,
    validate_finalizer_instance_spec as core_validate_finalizer_instance_spec,
    validate_finalizer_plan as core_validate_finalizer_plan,
    validate_finalizer_provider_spec as core_validate_finalizer_provider_spec,
    validate_finalizer_submission as core_validate_finalizer_submission,
    FinalizerAssignedBeadWire, FinalizerContextWire, FinalizerError,
    FinalizerInstanceResultWire, FinalizerInstanceSpecWire,
    FinalizerPlanInputWire, FinalizerPlanWire, FinalizerProviderSpecWire,
    FinalizerSubmissionEnvelopeWire, RemainingCommitWorkRequestWire,
    FINALIZER_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::fleet_attention::{
    self as core_fleet_attention, FleetAttentionEntryWire,
    FleetAttentionIntentWire, FleetAttentionInventoryRequestWire,
    FleetAttentionInventoryResponseWire, FleetAttentionLogicalIdentityWire,
    FleetAttentionNoticeLedgerEntryWire, FleetAttentionNotificationRowWire,
    FleetAttentionRequestWire,
};
pub(crate) use sase_core::fleet_catalog::{
    assemble_fleet_catalog as core_assemble_fleet_catalog,
    AssembleFleetCatalogRequestWire,
};
pub(crate) use sase_core::fleet_contract::{
    self as core_fleet_contract, AgentInstanceLocatorWire,
    CacheFreshnessRequestWire, CapabilitySetWire, ConnectionPlanWire,
    CursorReplayRequestWire, FleetCatalogAccumulationRequestWire,
    FleetCatalogQueryWire, FleetCatalogScopeWire,
    FleetContractError as FleetContractDomainError,
    FleetFederationNormalizeRequestWire, FleetLaunchDecisionRequestWire,
    FleetLaunchIntentWire, FleetLaunchRequestWire,
    FleetLogicalAgentCountsRequestWire, FleetSnapshotFreshnessWire,
    FocusFleetCountsRequestWire, FocusFleetFederationCountsRequestWire,
    FollowReconciliationRequestWire, FollowRecordWire,
    InstallationIdentityMigrateRequestWire,
    InstallationIdentityRotateRequestWire, LogicalAgentLocatorWire,
    OperationDecisionRequestWire, OwnerDisplayNameRequestWire,
    PayloadFingerprintRequestWire, ResolvedAgentProjectionRequestWire,
    ResolvedAgentSummaryWire, RuntimeDurationRequestWire,
};
pub(crate) use sase_core::fleet_follow_promotion::{
    followed_batch_family_promotions as core_followed_batch_family_promotions,
    FollowedBatchFamilyPromotionRequestWire,
};
pub(crate) use sase_core::fleet_mutation::{
    self as core_fleet_mutation, FleetMutationIntentWire,
    FleetMutationRequestWire,
};
pub(crate) use sase_core::gate_decision::{
    claim_gate_decision_execution_from_json as core_claim_gate_decision_execution_from_json,
    decide_gate_decision_acceptance_from_json as core_decide_gate_decision_acceptance_from_json,
    decide_gate_lifecycle_from_json as core_decide_gate_lifecycle_from_json,
    GateDecisionError, GATE_DECISION_WIRE_SCHEMA_VERSION,
    GATE_LIFECYCLE_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::gate_followup::{
    decide_gate_followup as core_decide_gate_followup,
    gate_followup_attempt_id as core_gate_followup_attempt_id,
    gate_followup_decision_request_from_json_value, GateFollowupError,
    GATE_FOLLOWUP_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::git_object_sharing::{
    plan_git_object_sharing as core_plan_git_object_sharing,
    GitObjectSharingError, GitObjectSharingPlanRequestWire,
    GIT_OBJECT_SHARING_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::git_query::{
    derive_git_workspace_name as core_derive_git_workspace_name,
    parse_git_branch_name as core_parse_git_branch_name,
    parse_git_conflicted_files as core_parse_git_conflicted_files,
    parse_git_local_changes as core_parse_git_local_changes,
    parse_git_name_status_z as core_parse_git_name_status_z,
};
pub(crate) use sase_core::glossary::{
    build_glossary_catalog as core_build_glossary_catalog,
    compile_glossary_catalog as core_compile_glossary_catalog,
    validate_glossary_entries as core_validate_glossary_entries,
    CompiledGlossaryCatalog as CoreCompiledGlossaryCatalog, GlossaryError,
    GlossaryInputEntryWire,
};
pub(crate) use sase_core::inline_code_ranges as core_inline_code_ranges;
pub(crate) use sase_core::machine_hood::{
    machine_hood_of as core_machine_hood_of,
    qualify_machine_agent_name as core_qualify_machine_agent_name,
    strip_machine_agent_name as core_strip_machine_agent_name,
    validate_machine_name as core_validate_machine_name,
};
pub(crate) use sase_core::machine_setup::{
    assess_machine_init_review as core_assess_machine_init_review,
    classify_tailnet_discovery as core_classify_tailnet_discovery,
    classify_tailnet_health as core_classify_tailnet_health,
    merge_machine_init_review as core_merge_machine_init_review,
    reconcile_machine_enrollments as core_reconcile_machine_enrollments,
    MachineInitReviewAssessmentRequestWire, MachineInitReviewMergeRequestWire,
    MachineReconcileRequestWire, MachineSetupError,
    TailnetDiscoveryRequestWire, TailnetHealthRequestWire,
    MACHINE_SETUP_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::managed_origin::{
    decide_managed_origin_reconciliation as core_decide_managed_origin_reconciliation,
    ManagedOriginReconciliationRequestWire,
    MANAGED_ORIGIN_RECONCILIATION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::managed_tmp::{
    reap_managed_tmpdir as core_reap_managed_tmpdir, ManagedTmpReapError,
    ManagedTmpReapRequestWire, MANAGED_TMP_REAP_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::markdown_link_refs::{
    allocate_markdown_reference_label as core_allocate_markdown_reference_label,
    append_markdown_reference_definitions as core_append_markdown_reference_definitions,
    scan_markdown_reference_links as core_scan_markdown_reference_links,
    MarkdownReferenceDefinitionWire, MarkdownReferenceScanWire,
    MARKDOWN_LINK_REFS_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::migration::{
    acquire_bounded_lock as core_migration_acquire_bounded_lock,
    classify as core_migration_residue_classify,
    convert_gate_bundles_apply as core_migration_gate_bundles_apply,
    convert_gate_bundles_plan as core_migration_gate_bundles_plan,
    convert_gate_bundles_verify as core_migration_gate_bundles_verify,
    convert_patch_records_apply as core_migration_patch_records_apply,
    convert_patch_records_plan as core_migration_patch_records_plan,
    convert_patch_records_verify as core_migration_patch_records_verify,
    fingerprint as core_migration_fingerprint,
    plan_next_step as core_migration_plan_next_step,
    reconcile_plan as core_migration_reconcile_procs,
    tree_digest as core_migration_tree_digest, GateBundleConvertFactsWire,
    MigrationCanonicalProcRefWire, MigrationDigestError, MigrationHeldLock,
    MigrationJournalRecord, MigrationLegacyProcRowWire, MigrationLockError,
    MigrationManifest, MigrationResidueEntryWire, MigrationResidueFactsWire,
    PatchRecordsConvertFactsWire, MIGRATION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::model_route::{
    select_epic_land_model as core_select_epic_land_model,
    size_model_route_from_name as core_size_model_route_from_name,
    ModelRouteError as ModelRouteDomainError,
};
pub(crate) use sase_core::notifications::{
    append_notification as core_append_notification,
    append_notification_counts as core_append_notification_counts,
    append_notification_plus_one as core_append_notification_plus_one,
    apply_notification_state_update as core_apply_notification_state_update,
    apply_notification_state_update_counts as core_apply_notification_state_update_counts,
    classify_notification_tabs as core_classify_notification_tabs,
    current_unix_time as core_current_unix_time,
    mark_pending_action_handled as core_mark_pending_action_handled,
    merge_pending_action_transport as core_merge_pending_action_transport,
    pending_action_from_notification as core_pending_action_from_notification,
    pending_action_transport as core_pending_action_transport,
    read_current_notifications_snapshot as core_read_current_notifications_snapshot,
    read_notifications_snapshot_with_options as core_read_notifications_snapshot_with_options,
    read_pending_action_store as core_read_pending_action_store,
    register_pending_action as core_register_pending_action,
    remove_pending_action as core_remove_pending_action,
    resolve_notification_deliveries as core_resolve_notification_deliveries,
    rewrite_notifications as core_rewrite_notifications,
    rewrite_notifications_counts as core_rewrite_notifications_counts,
    upsert_notification as core_upsert_notification,
    NotificationPlusOneRequestWire, NotificationRuleWire,
    NotificationStateUpdateWire, NotificationUpsertRequestWire,
    NotificationWire, PendingActionTransportRequestWire, PendingActionWire,
};
pub(crate) use sase_core::pending_commit_checkpoint::{
    decide_pending_commit_checkpoint_recovery as core_decide_pending_commit_checkpoint_recovery,
    PendingCommitCheckpointRequestWire,
    PENDING_COMMIT_CHECKPOINT_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::perf_logs::{
    perf_logs_query as core_perf_logs_query, PerfLogsQueryWire,
};
pub(crate) use sase_core::plan::{
    canonicalize_plan_reference as core_canonicalize_plan_reference,
    parse_plan_reference as core_parse_plan_reference,
    parse_sdd_artifact_link as core_parse_sdd_artifact_link,
    parse_sdd_plan_header_block as core_parse_sdd_plan_header_block,
    plan_frontmatter_schema as core_plan_frontmatter_schema,
    plan_validate_with_mode as core_plan_validate_with_mode,
    remove_sdd_plan_header_section as core_remove_sdd_plan_header_section,
    render_plan_reference as core_render_plan_reference,
    render_sdd_artifact_link as core_render_sdd_artifact_link,
    render_sdd_plan_header_block as core_render_sdd_plan_header_block,
    replace_sdd_plan_header_block as core_replace_sdd_plan_header_block,
    resolve_plan_reference as core_resolve_plan_reference,
    search_plans as core_plan_search,
    upsert_sdd_artifact_link as core_upsert_sdd_artifact_link,
    upsert_sdd_plan_header_section as core_upsert_sdd_plan_header_section,
    PlanError, SddPlanHeaderSectionWire, PLAN_HEADER_BLOCK_WIRE_SCHEMA_VERSION,
    PLAN_REFERENCE_RESOLUTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::procs::{
    append_proc as core_append_proc,
    apply_proc_runtime_retention as core_apply_proc_runtime_retention,
    begin_proc_settlement as core_begin_proc_settlement,
    claim_proc_supervisor as core_claim_proc_supervisor,
    finish_proc as core_finish_proc, prune_procs as core_prune_procs,
    read_procs_snapshot as core_read_procs_snapshot,
    request_proc_stop as core_request_proc_stop,
    reserve_proc as core_reserve_proc, update_proc as core_update_proc,
    ProcFinishWire, ProcReserveWire, ProcRuntimeRetentionRequestWire,
    ProcSettlementWire, ProcStopRequestWire, ProcStoreError,
    ProcSupervisorClaimWire, ProcUpdateWire, ProcWire,
    PROC_RUNTIME_RETENTION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::project_spec::{
    apply_project_aliases_update as core_apply_project_aliases_update,
    apply_project_lifecycle_update as core_apply_project_lifecycle_update,
    apply_project_name_update as core_apply_project_name_update,
    list_project_records as core_list_project_records,
    read_project_lifecycle_from_content as core_read_project_lifecycle_from_content,
};
pub(crate) use sase_core::prompt_archive::{
    prompt_archive_inventory as core_prompt_archive_inventory,
    PromptArchiveInventoryRequestWire,
    PROMPT_ARCHIVE_INVENTORY_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::prompt_artifact::{
    artifact_pool_filename as core_artifact_pool_filename,
    parse_prompt_artifact_manifest as core_parse_prompt_artifact_manifest,
    render_prompt_artifact_record as core_render_prompt_artifact_record,
    rewrite_prompt_artifact_links as core_rewrite_prompt_artifact_links,
    select_manifest_records as core_select_prompt_artifact_manifest_records,
    PromptArtifactRecord, PROMPT_ARTIFACT_MANIFEST_SCHEMA_VERSION,
};
pub(crate) use sase_core::prompt_history_filter::{
    build_prompt_history_seed as core_build_prompt_history_seed,
    compile_prompt_history_query as core_compile_prompt_history_query,
    encode_prompt_history_literal as core_encode_prompt_history_literal,
    match_prompt_history_rows as core_match_prompt_history_rows,
    CompiledPromptHistoryQueryWire, PromptHistoryProjectIdentityWire,
    PromptHistoryRowFactsWire, PromptHistorySeedRequestWire,
};
pub(crate) use sase_core::prompt_stash::{
    append_prompt_stash as core_append_prompt_stash,
    pop_prompt_stash as core_pop_prompt_stash,
    read_prompt_stash_snapshot as core_read_prompt_stash_snapshot,
    rewrite_prompt_stash as core_rewrite_prompt_stash,
    set_prompt_stash_pinned as core_set_prompt_stash_pinned,
    PromptStashEntryWire, PromptStashStoreError,
};
pub(crate) use sase_core::provider_disable::{
    clear_provider_disable as core_clear_provider_disable,
    get_provider_disables as core_get_provider_disables,
    set_provider_disable_relative as core_set_provider_disable_relative,
    set_provider_disable_until as core_set_provider_disable_until,
    try_set_provider_disable_relative as core_try_set_provider_disable_relative,
    try_set_provider_disable_until as core_try_set_provider_disable_until,
    ProviderDisableError as ProviderDisableDomainError, ProviderDisableMode,
};
pub(crate) use sase_core::provider_priority::{
    classify_provider_availability as core_classify_provider_availability,
    classify_provider_availability_many as core_classify_provider_availability_many,
    clear_provider_priority as core_clear_provider_priority,
    decode_provider_priority_bytes as core_decode_provider_priority_bytes,
    get_provider_priority as core_get_provider_priority,
    get_provider_routing_context as core_get_provider_routing_context,
    peek_provider_priority as core_peek_provider_priority,
    pool_eligibility_mask as core_pool_eligibility_mask,
    pool_reservation_eligible as core_pool_reservation_eligible,
    provider_routing_context_from_parts as core_provider_routing_context_from_parts,
    set_provider_priority_relative as core_set_provider_priority_relative,
    set_provider_priority_until as core_set_provider_priority_until,
    ProviderAvailabilityFactsWire, ProviderAvailabilityWire,
    ProviderPriorityError as ProviderPriorityDomainError,
    ProviderPriorityTargetFactsWire, ProviderPriorityWire,
    ProviderRoutingContextWire,
};
pub(crate) use sase_core::provider_usage::{
    admit_provider_usage_refresh as core_admit_provider_usage_refresh,
    classify_freshness as core_classify_freshness,
    evaluate_provider_usage_refresh_due as core_evaluate_provider_usage_refresh_due,
    format_remaining_text as core_format_remaining_text,
    list_provider_usage_refresh_reservations as core_list_refresh_reservations,
    load_provider_usage_store_with_floors as core_load_provider_usage_with_floors,
    mark_provider_usage_hot as core_mark_provider_usage_hot,
    mark_provider_usage_refresh_due as core_mark_provider_usage_refresh_due,
    normalize_agy_usage as core_normalize_agy_usage,
    normalize_grok_billing as core_normalize_grok_billing,
    normalize_muse_usage as core_normalize_muse_usage,
    prepare_provider_usage_account_context as core_prepare_provider_usage_account_context,
    project_usage_indicator as core_project_usage_indicator,
    project_usage_snapshot as core_project_usage_snapshot,
    provider_usage_state_path as core_provider_usage_state_path,
    record_provider_usage_observation as core_record_provider_usage_observation,
    record_provider_usage_refresh_attempt as core_record_provider_usage_refresh_attempt,
    release_provider_usage_refresh as core_release_provider_usage_refresh,
    remaining_percent as core_remaining_percent,
    reserve_provider_usage_refresh as core_reserve_provider_usage_refresh,
    summarize_usage_windows as core_summarize_usage_windows,
    usage_window_applies as core_usage_window_applies,
    validate_usage_indicator_config as core_validate_usage_indicator_config,
    validate_usage_observation as core_validate_usage_observation,
    MarkProviderUsageHotRequestWire,
    ProviderUsageError as ProviderUsageDomainError,
    ProviderUsageNormalizeAgyUsageRequestWire,
    ProviderUsageNormalizeGrokBillingRequestWire,
    ProviderUsageNormalizeMuseUsageRequestWire, ProviderUsageObservationWire,
    ProviderUsageRefreshAdmitRequestWire, ProviderUsageRefreshAttemptWire,
    ProviderUsageRefreshDueRequestWire, ProviderUsageRefreshMarkDueRequestWire,
    ProviderUsageRefreshReservationRequestWire,
    ProviderUsageStoreError as ProviderUsageStoreDomainError,
    UsageApplicabilityWire, UsageIndicatorProjectionRequestWire,
    UsagePublicWindowWire, DEFAULT_USAGE_CADENCE_SECONDS,
    DEFAULT_USAGE_CRITICAL_PERCENT, DEFAULT_USAGE_WARN_PERCENT,
    PROVIDER_USAGE_INDICATOR_SCHEMA_VERSION,
    PROVIDER_USAGE_OBSERVATION_SCHEMA_VERSION,
    PROVIDER_USAGE_PUBLIC_SCHEMA_VERSION, PROVIDER_USAGE_STORE_SCHEMA_VERSION,
    USAGE_COLLECTOR_FAILING_THRESHOLD,
};
pub(crate) use sase_core::query::types::{QueryErrorWire, QueryExprWire};
pub(crate) use sase_core::query::{
    canonicalize_query_with_profile as core_canonicalize_query_with_profile,
    compile_query_with_profile as core_compile_query_with_profile,
    parse_query_with_profile as core_parse_query_with_profile,
    tokenize_query_with_profile as core_tokenize_query_with_profile,
    try_evaluate_query_many_in_corpus as core_try_evaluate_query_many_in_corpus,
    CompiledQueryProfile, QueryCorpus as CoreQueryCorpus, QueryFieldValues,
    QueryPredicateFacts, QueryProgram as CoreQueryProgram, QueryRow,
};
pub(crate) use sase_core::referenced_by::{
    parse_referenced_by_block as core_parse_referenced_by_block,
    remove_referenced_by_block as core_remove_referenced_by_block,
    render_referenced_by_block as core_render_referenced_by_block,
    strip_referenced_by_block as core_strip_referenced_by_block,
    upsert_referenced_by_block as core_upsert_referenced_by_block,
    ReferencedByTableWire, REFERENCED_BY_BLOCK_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::repository_resolution::{
    canonical_repository_identity as core_canonical_repository_identity,
    repository_resolution_wire_schema_version as core_repository_resolution_wire_schema_version,
    resolve_repository_reference as core_resolve_repository_reference,
    RepositoryResolutionRequestWire,
};
pub(crate) use sase_core::retryability::{
    classify_failure_retryability as core_classify_failure_retryability,
    retryability_wire_schema_version as core_retryability_wire_schema_version,
    FailureObservationWire, RetryabilityVerdictWire,
};
pub(crate) use sase_core::runner_limit_override::{
    clear_runner_limit_override as core_clear_runner_limit_override,
    get_runner_limit_override as core_get_runner_limit_override,
    set_runner_limit_override_relative as core_set_runner_limit_override_relative,
    set_runner_limit_override_until as core_set_runner_limit_override_until,
    RunnerLimitOverrideError as RunnerLimitOverrideDomainError,
};
pub(crate) use sase_core::scan_directive_owned_fences as core_scan_directive_owned_fences;
pub(crate) use sase_core::service::config::{
    compose_service_config as core_compose_service_config,
    ServiceConfigComposeRequestWire,
};
pub(crate) use sase_core::service::restart::{
    decide_service_restart as core_decide_service_restart,
    ServiceRestartRequestWire,
};
pub(crate) use sase_core::service::state::{
    mutate_service_state as core_mutate_service_state,
    read_service_state as core_read_service_state,
    ServiceStateError as ServiceStateDomainError, ServiceStateMutationWire,
};
pub(crate) use sase_core::service::status::{
    build_service_status as core_build_service_status,
    read_service_status_snapshot as core_read_service_status_snapshot,
    resolve_service_enablement_for_entry as core_resolve_service_enablement_for_entry,
    write_service_status_snapshot as core_write_service_status_snapshot,
    ServiceStatusError as ServiceStatusDomainError, ServiceStatusRequestWire,
    ServiceStatusSnapshotWire,
};
pub(crate) use sase_core::sidecar_publication::{
    decide_sidecar_publication_after_push as core_decide_sidecar_publication_after_push,
    SidecarPublicationDecisionWire,
};
pub(crate) use sase_core::snippet_session::{
    apply_session_event as core_apply_snippet_session_event,
    SnippetSessionEvent, SnippetSessionState,
};
pub(crate) use sase_core::source_language::{
    logical_filename_from_hints as core_logical_filename_from_hints,
    resolve_source_language as core_resolve_source_language,
    source_filename_hints_from_json_value,
    source_language_request_from_json_value,
    SOURCE_LANGUAGE_PREFIX_BUDGET_BYTES, SOURCE_LANGUAGE_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::status::{
    apply_status_update as core_apply_status_update,
    is_valid_transition as core_is_valid_transition,
    plan_status_transition as core_plan_status_transition,
    read_status_from_lines as core_read_status_from_lines,
    remove_workspace_suffix as core_remove_workspace_suffix,
    StatusTransitionRequestWire,
};
pub(crate) use sase_core::tail_text_by_lines_and_chars as core_tail_text_by_lines_and_chars;
pub(crate) use sase_core::task_type::{
    parse_task_type_snapshot as core_parse_task_type_snapshot,
    render_task_type_body as core_render_task_type_body,
    serialize_task_type_snapshot as core_serialize_task_type_snapshot,
    task_type_spec_digest as core_task_type_spec_digest,
    validate_task_type_field_values as core_validate_task_type_field_values,
    validate_task_type_spec as core_validate_task_type_spec, TaskTypeError,
    TaskTypeSnapshotWire, TaskTypeSpecWire, TASK_TYPE_SPEC_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::telemetry::{
    cleanup_matching_labels as core_telemetry_cleanup_matching_labels,
    prune as core_telemetry_prune,
    query_instant as core_telemetry_query_instant,
    query_range as core_telemetry_query_range,
    record_batch as core_telemetry_record_batch,
    store_stats as core_telemetry_store_stats, TelemetryCleanupRequestWire,
    TelemetryInstantQueryWire, TelemetryPruneRequestWire,
    TelemetryRangeQueryWire, TelemetryRecordBatchWire,
};
pub(crate) use sase_core::tool_run::{
    append_event as core_tool_run_append_event, begin as core_tool_run_begin,
    canonicalize_tool_fingerprint as core_tool_run_canonicalize_fingerprint,
    finish as core_tool_run_finish, list_runs as core_tool_run_list,
    normalize_tool_definition as core_tool_run_normalize_definition,
    observe as core_tool_run_observe, reconcile as core_tool_run_reconcile,
    retention_apply as core_tool_run_retention_apply,
    retention_preview as core_tool_run_retention_preview,
    show_run as core_tool_run_show, store_stats as core_tool_run_store_stats,
    summarize as core_tool_run_summary,
    unknown_evidence as core_tool_run_unknown_evidence, ToolDefinitionWire,
    ToolFingerprintWire, ToolRunAppendRequestWire, ToolRunBeginRequestWire,
    ToolRunFinishRequestWire, ToolRunListRequestWire,
    ToolRunObserveRequestWire, ToolRunReconcileRequestWire,
    ToolRunRetentionRequestWire, ToolRunShowRequestWire,
    ToolRunSummaryRequestWire, TOOL_RUN_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::vcs_log::{
    aggregate_commit_log as core_aggregate_commit_log,
    classify_commit_origin as core_classify_commit_origin,
    classify_commit_presence as core_classify_commit_presence,
    classify_commit_types_for_commit as core_classify_commit_types_for_commit,
    parse_git_log as core_parse_git_log,
    parse_merge_summary as core_parse_merge_summary, CommitOriginWire,
    CommitPresenceWire, VcsCommitWire, VCS_LOG_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::wire::ChangeSpecWire;
pub(crate) use sase_core::wire::{CommentWire, HookWire, MentorWire};
pub(crate) use sase_core::CODE_VALUE_WIRE_SCHEMA_VERSION;
pub(crate) use sase_core::{
    collect_hold_fields_with_flags as core_collect_hold_fields_with_flags,
    collect_queue_fields_with_flags as core_collect_queue_fields_with_flags,
    format_hold_directive as core_format_hold_directive,
    format_queue_directive as core_format_queue_directive,
    hold_fields_to_selectors_with_identity as core_hold_fields_to_selectors_with_identity,
    normalize_persisted_queue_capacity as core_normalize_persisted_queue_capacity,
    parse_queue_capacity_with_flags as core_parse_queue_capacity_with_flags,
    queue_directive_flag_key as core_queue_directive_flag_key, HoldFieldsWire,
    HoldOccurrenceWire, HoldSelectorIdentityWire, QueueFieldsWire,
    QueueOccurrenceWire,
};
pub(crate) use sase_core::{
    compose_snippet_catalog as core_compose_snippet_catalog,
    editor_detect_model_alias_shortcut_context as core_detect_model_alias_shortcut_context,
    editor_filter_explicit_model_shortcut_entries as core_filter_explicit_model_shortcut_entries,
    editor_filter_model_alias_shortcut_entries as core_filter_model_alias_shortcut_entries,
    editor_model_shortcut_context as core_model_shortcut_context,
    editor_model_shortcut_edit as core_model_shortcut_edit,
    editor_plan_argument_colon_to_parentheses_edit as core_plan_argument_colon_to_parentheses_edit,
    editor_plan_argument_double_colon_to_parentheses_edit as core_plan_argument_double_colon_to_parentheses_edit,
    editor_plan_model_alias_shortcut_edit as core_plan_model_alias_shortcut_edit,
    filter_model_completion_entries as core_filter_model_completion_entries,
    load_editor_snippet_catalog as core_load_editor_snippet_catalog,
    resolve_xprompt_skill_definition as core_resolve_xprompt_skill_definition,
    validate_snippet_trigger as core_validate_snippet_trigger, EditorPosition,
    EditorSnippetCatalogRequestWire, ModelCompletionEntryWire,
    XpromptCatalogLoadOptions, XpromptCatalogResourcePaths,
    XpromptSkillDefinitionRequestWire, MODEL_COMPLETION_ENTRY_WIRE_FIELDS,
    XPROMPT_SKILL_DEFINITION_WIRE_SCHEMA_VERSION,
};
pub(crate) use sase_core::{
    runner_capacity_policy_schema_version as core_runner_capacity_policy_schema_version,
    runner_capacity_snapshot as core_runner_capacity_snapshot,
    RunnerCapacityRequestWire,
};
pub(crate) use sase_core::{
    ServiceEnablementOverrideWire, ServiceProcConfigWire,
};
pub(crate) use serde::de::DeserializeOwned;
pub(crate) use serde::ser::{
    self, Impossible, SerializeMap, SerializeSeq, SerializeStruct,
    SerializeStructVariant, SerializeTuple, SerializeTupleStruct,
    SerializeTupleVariant, Serializer,
};
pub(crate) use serde::Deserialize;
pub(crate) use serde_json::{Map as JsonMap, Value as JsonValue};
pub(crate) use std::cmp::Ordering;
pub(crate) use std::collections::BTreeMap;
pub(crate) use std::fs::File;
pub(crate) use std::path::PathBuf;
pub(crate) use std::process::{Child, Command, Stdio};
pub(crate) use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};
