//! Compare Rust JSON output against the Python `wire.py` shape.
//!
//! The Python side is captured as a fixture string rather than invoked at
//! test time so this crate stays runnable without a Python toolchain. The
//! fixture is generated by:
//!
//! ```text
//! python -c "
//! import json
//! from sase.core.wire import (
//!     ChangeSpecWire, SourceSpanWire, CommitWire, HookWire, HookStatusLineWire,
//!     CommentWire, MentorWire, MentorStatusLineWire, TimestampWire, DeltaWire,
//!     CHANGESPEC_WIRE_SCHEMA_VERSION, to_json_dict,
//! )
//! cs = ChangeSpecWire(
//!     schema_version=CHANGESPEC_WIRE_SCHEMA_VERSION,
//!     name='rust_workspace',
//!     project_basename='myproj',
//!     file_path='myproj.sase',
//!     source_span=SourceSpanWire(file_path='myproj.sase', start_line=5, end_line=42),
//!     status='WIP',
//!     parent='parent_cl',
//!     cl_or_pr='123',
//!     bug=None,
//!     description='first line\\nsecond line',
//!     test_targets=['//foo:bar'],
//!     commits=[CommitWire(number=1, note='init', suffix='@', suffix_type='running', body=['body line'])],
//!     hooks=[HookWire(command='just lint', status_lines=[HookStatusLineWire(commit_entry_num='1', timestamp='20260429_010101', status='OK', duration='3s')])],
//!     comments=[CommentWire(reviewer='alice', file_path='src/foo.rs')],
//!     mentors=[MentorWire(entry_id='m1', profiles=['default'], status_lines=[MentorStatusLineWire(profile_name='default', mentor_name='claude', status='RUNNING', timestamp=None, suffix='mentor_claude-123-20260429_010101', suffix_type='running_agent')], is_draft=False)],
//!     timestamps=[TimestampWire(timestamp='20260429_010101', event_type='created', detail='')],
//!     deltas=[DeltaWire(path='src/lib.rs', change_type='A')],
//! )
//! print(json.dumps(to_json_dict(cs), sort_keys=True))
//! "
//! ```
//!
//! Keep the fixture sorted by key (`sort_keys=True`) so the comparison is
//! independent of declaration order — Phase 1D will introduce the byte-for-
//! byte ordered comparison.

use sase_core::{
    ChangeSpecWire, CommentWire, CommitWire, DeltaWire, HookStatusLineWire,
    HookWire, MentorStatusLineWire, MentorWire, SourceSpanWire, TimestampWire,
    CHANGESPEC_WIRE_SCHEMA_VERSION,
};
use serde_json::Value;

const PYTHON_FIXTURE: &str = r#"{
    "schema_version": 1,
    "name": "rust_workspace",
    "project_basename": "myproj",
    "file_path": "myproj.sase",
    "source_span": {
        "file_path": "myproj.sase",
        "start_line": 5,
        "end_line": 42
    },
    "status": "WIP",
    "parent": "parent_cl",
    "cl_or_pr": "123",
    "bug": null,
    "description": "first line\nsecond line",
    "test_targets": ["//foo:bar"],
    "commits": [
        {
            "number": 1,
            "note": "init",
            "chat": null,
            "diff": null,
            "plan": null,
            "proposal_letter": null,
            "suffix": "@",
            "suffix_type": "running",
            "body": ["body line"]
        }
    ],
    "hooks": [
        {
            "command": "just lint",
            "status_lines": [
                {
                    "commit_entry_num": "1",
                    "timestamp": "20260429_010101",
                    "status": "OK",
                    "duration": "3s",
                    "suffix": null,
                    "suffix_type": null,
                    "summary": null
                }
            ]
        }
    ],
    "comments": [
        {
            "reviewer": "alice",
            "file_path": "src/foo.rs",
            "suffix": null,
            "suffix_type": null
        }
    ],
    "mentors": [
        {
            "entry_id": "m1",
            "profiles": ["default"],
            "status_lines": [
                {
                    "profile_name": "default",
                    "mentor_name": "claude",
                    "status": "RUNNING",
                    "timestamp": null,
                    "duration": null,
                    "suffix": "mentor_claude-123-20260429_010101",
                    "suffix_type": "running_agent"
                }
            ],
            "is_draft": false
        }
    ],
    "timestamps": [
        {
            "timestamp": "20260429_010101",
            "event_type": "created",
            "detail": ""
        }
    ],
    "deltas": [
        {
            "path": "src/lib.rs",
            "change_type": "A"
        }
    ]
}"#;

fn rust_changespec() -> ChangeSpecWire {
    ChangeSpecWire {
        schema_version: CHANGESPEC_WIRE_SCHEMA_VERSION,
        name: "rust_workspace".to_string(),
        project_basename: "myproj".to_string(),
        file_path: "myproj.sase".to_string(),
        source_span: SourceSpanWire {
            file_path: "myproj.sase".to_string(),
            start_line: 5,
            end_line: 42,
        },
        status: "WIP".to_string(),
        parent: Some("parent_cl".to_string()),
        cl_or_pr: Some("123".to_string()),
        bug: None,
        description: "first line\nsecond line".to_string(),
        test_targets: vec!["//foo:bar".to_string()],
        commits: vec![CommitWire {
            number: 1,
            note: "init".to_string(),
            chat: None,
            diff: None,
            plan: None,
            proposal_letter: None,
            suffix: Some("@".to_string()),
            suffix_type: Some("running".to_string()),
            body: vec!["body line".to_string()],
        }],
        hooks: vec![HookWire {
            command: "just lint".to_string(),
            status_lines: vec![HookStatusLineWire {
                commit_entry_num: "1".to_string(),
                timestamp: "20260429_010101".to_string(),
                status: "OK".to_string(),
                duration: Some("3s".to_string()),
                suffix: None,
                suffix_type: None,
                summary: None,
            }],
        }],
        comments: vec![CommentWire {
            reviewer: "alice".to_string(),
            file_path: "src/foo.rs".to_string(),
            suffix: None,
            suffix_type: None,
        }],
        mentors: vec![MentorWire {
            entry_id: "m1".to_string(),
            profiles: vec!["default".to_string()],
            status_lines: vec![MentorStatusLineWire {
                profile_name: "default".to_string(),
                mentor_name: "claude".to_string(),
                status: "RUNNING".to_string(),
                timestamp: None,
                duration: None,
                suffix: Some("mentor_claude-123-20260429_010101".to_string()),
                suffix_type: Some("running_agent".to_string()),
            }],
            is_draft: false,
        }],
        timestamps: vec![TimestampWire {
            timestamp: "20260429_010101".to_string(),
            event_type: "created".to_string(),
            detail: "".to_string(),
        }],
        deltas: vec![DeltaWire {
            path: "src/lib.rs".to_string(),
            change_type: "A".to_string(),
        }],
    }
}

#[test]
fn rust_json_equals_python_fixture() {
    let rust_value: Value = serde_json::to_value(rust_changespec()).unwrap();
    let python_value: Value = serde_json::from_str(PYTHON_FIXTURE).unwrap();
    assert_eq!(rust_value, python_value);
}

#[test]
fn python_fixture_deserializes_into_rust_type() {
    // The reverse direction: a Rust parser must accept Python-shaped JSON
    // (modulo defaults) without losing information.
    let cs: ChangeSpecWire = serde_json::from_str(PYTHON_FIXTURE).unwrap();
    assert_eq!(cs, rust_changespec());
}
